# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Omni-AI Technology Blog
tagline:          'High Performance, Decoupled Architecture'
description:      'Suite of NPU native accelerators and an expanding feature set'
url:              http://omni-ai-npu.github.io
baseurl:          /

author:
  name:           'Howard Huang'
  url:            https://twitter.com/nopainkiller

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/omni-ai-npu/omni-infer
